# Generated by Django 3.2 on 2022-02-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyerreg',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Buyer ID')),
                ('bname', models.CharField(max_length=25, verbose_name='Buyer Name')),
                ('phoneno', models.IntegerField(verbose_name='Phone No')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('username', models.CharField(max_length=25, verbose_name='User Name')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
                ('rights', models.CharField(default='EN', max_length=25, verbose_name='Type Of User')),
            ],
        ),
        migrations.CreateModel(
            name='Ownerreg',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Owner ID')),
                ('oname', models.CharField(max_length=25, verbose_name='Owner Name')),
                ('phoneno', models.IntegerField(verbose_name='Phone No')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='ID Proof')),
                ('username', models.CharField(max_length=25, verbose_name='User Name')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
                ('rights', models.CharField(default='EN', max_length=25, verbose_name='Type Of User')),
            ],
        ),
    ]
