# Generated by Django 3.2 on 2022-02-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerreg',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='ownerreg',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='User Name'),
        ),
    ]
