# Generated by Django 3.2 on 2022-02-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_auto_20220225_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerreg',
            name='username',
            field=models.CharField(max_length=25, unique='true', verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='ownerreg',
            name='username',
            field=models.CharField(max_length=25, unique='true', verbose_name='User Name'),
        ),
    ]
