# Generated by Django 3.2 on 2022-02-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_auto_20220225_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerreg',
            name='rights',
            field=models.CharField(default='N', max_length=25, verbose_name='Type Of User'),
        ),
        migrations.AlterField(
            model_name='ownerreg',
            name='rights',
            field=models.CharField(default='N', max_length=25, verbose_name='Type Of User'),
        ),
    ]
