# Generated by Django 3.2 on 2022-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_auto_20220226_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerreg',
            name='rights',
            field=models.CharField(max_length=25, verbose_name='Type Of User'),
        ),
    ]
