# Generated by Django 3.2 on 2022-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0005_alter_buyerreg_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Property ID')),
                ('oid', models.IntegerField(verbose_name='Owner ID')),
                ('ptype', models.CharField(choices=[('RA', 'Residential Apartment'), ('RL', 'Residential Land'), ('RHV', 'Residential House/Villa'), ('RO', 'Residential Other'), ('CS', 'Commercial Shop'), ('CO', 'Comercial Office'), ('CL', 'Commercial Land'), ('CB', 'Commercial Building'), ('COO', 'Commercial Other'), ('IB', 'Industrial Building'), ('IL', 'Industrial Land'), ('AL', 'Agricultural Land')], max_length=3, verbose_name='Property Type')),
                ('ttype', models.CharField(choices=[('B', 'BUY'), ('R', 'RENT')], max_length=10, verbose_name='Transacaction Type')),
                ('otype', models.CharField(choices=[('F', 'FIRST OWNER'), ('S', 'SECOND OWNER'), ('O', 'OTHER')], max_length=10, verbose_name='Ownership Type')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('des', models.CharField(max_length=500, verbose_name='Description')),
                ('state', models.CharField(default='Kerala', max_length=1, verbose_name='State')),
                ('district', models.CharField(choices=[('AL', 'Alappuzha'), ('ER', 'Eranakulam'), ('ID', 'Iduki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthiita'), ('TV', 'Thiruvananthapuram'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], max_length=2, verbose_name='District')),
                ('town', models.CharField(max_length=20, verbose_name='Town')),
                ('pincode', models.IntegerField(verbose_name='Pin Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phoneno', models.IntegerField(verbose_name='Phone NO')),
                ('builtarea', models.IntegerField(verbose_name='Built Area')),
                ('p1', models.ImageField(upload_to='property/', verbose_name='Photo1')),
                ('p2', models.ImageField(upload_to='property/', verbose_name='Photo2')),
                ('p3', models.ImageField(upload_to='property/', verbose_name='Photo5')),
                ('p4', models.ImageField(upload_to='property/', verbose_name='Photo4')),
                ('p5', models.ImageField(upload_to='property/', verbose_name='Photo5')),
                ('rights', models.CharField(default='P', max_length=2, verbose_name='State Of Property')),
            ],
        ),
    ]
