# Generated by Django 3.2 on 2022-03-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0006_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='oname',
            field=models.CharField(default=0, max_length=30, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Eranakulam', 'Eranakulam'), ('Iduki', 'Iduki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthiita', 'Pathanamthiita'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], max_length=20, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='property',
            name='otype',
            field=models.CharField(choices=[('FIRST OWNER', 'FIRST OWNER'), ('SECOND OWNER', 'SECOND OWNER'), ('OTHER', 'OTHER')], max_length=20, verbose_name='Ownership Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ptype',
            field=models.CharField(choices=[('Residential Apartment', 'Residential Apartment'), ('Residential Land', 'Residential Land'), ('Residential House/Villa', 'Residential House/Villa'), ('Residential Other', 'Residential Other'), ('Commercial Shop', 'Commercial Shop'), ('Comercial Office', 'Comercial Office'), ('Commercial Land', 'Commercial Land'), ('Commercial Building', 'Commercial Building'), ('Commercial Other', 'Commercial Other'), ('Industrial Building', 'Industrial Building'), ('Industrial Land', 'Industrial Land'), ('Agricultural Land', 'Agricultural Land')], max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(default='Kerala', max_length=6, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ttype',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], max_length=10, verbose_name='Transacaction Type'),
        ),
    ]
