# Generated by Django 3.2 on 2022-03-07 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0007_auto_20220307_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brqst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqno', models.IntegerField(verbose_name='Request No')),
                ('rqdate', models.DateField(default=datetime.date.today, verbose_name='Request Date')),
                ('bid', models.IntegerField(verbose_name='Buyer ID')),
                ('bname', models.CharField(max_length=20, verbose_name='Buyer Name')),
                ('pid', models.IntegerField(verbose_name='Propertyid')),
                ('price', models.IntegerField(verbose_name='price')),
                ('qprice', models.IntegerField(verbose_name='Requested Price')),
                ('rights', models.CharField(default='NS', max_length=3, verbose_name='Rights')),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='oname',
            field=models.CharField(max_length=30, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rights',
            field=models.CharField(default='NS', max_length=2, verbose_name='State Of Property'),
        ),
    ]
