# Generated by Django 3.2 on 2022-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0008_auto_20220307_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.IntegerField(verbose_name='Purchase NO')),
                ('pdate', models.IntegerField(verbose_name='Purchase Date')),
                ('pid', models.IntegerField(verbose_name='Property ID')),
                ('bid', models.IntegerField(verbose_name='Buyer ID')),
                ('bname', models.CharField(max_length=30, verbose_name='Buyer Name')),
                ('cardno', models.CharField(max_length=30, verbose_name='Card NO')),
                ('amtpaid', models.IntegerField(verbose_name='Amount Paid')),
            ],
        ),
    ]
