# Generated by Django 3.2 on 2022-03-08 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0011_auto_20220308_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pdate',
            field=models.IntegerField(default=datetime.date.today, verbose_name='Purchase Date'),
        ),
    ]
