# Generated by Django 3.2 on 2022-03-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0012_alter_purchase_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Purchase Date'),
        ),
    ]
