# Generated by Django 3.2 on 2022-03-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0013_alter_purchase_pdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brqst',
            name='id',
        ),
        migrations.AddField(
            model_name='brqst',
            name='oid',
            field=models.IntegerField(default=0, verbose_name='Owner ID'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Actual Price'),
        ),
        migrations.AlterField(
            model_name='brqst',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='brqst',
            name='rqno',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Request No'),
        ),
    ]
