# Generated by Django 3.2 on 2022-03-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0015_purchase_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='rqno',
            field=models.IntegerField(default=0, verbose_name='Request No'),
        ),
    ]
