# Generated by Django 3.2 on 2022-03-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0016_purchase_rqno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='Property ID')),
                ('tcount', models.IntegerField(default=0, verbose_name='No Of Counts')),
            ],
        ),
    ]
