# Generated by Django 3.2 on 2022-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0017_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='oname',
            field=models.CharField(default='x', max_length=20, verbose_name='Owner Name'),
        ),
    ]
